#include <stdio.h>

/**
 * main - Prints the first 98 Fibonacci numbers, separated by comma and space.
 *
 * Description: Fibonacci sequence generated by adding the previous two terms.
 *
 * Return: Always 0 (Success)
 */
int main(void)
{
	int count;
	unsigned long int fib1 = 1, fib2 = 2, next;

	printf("%lu, %lu", fib1, fib2);

	for (count = 2; count < 98; count++)
	{
		next = fib1 + fib2;
		printf(", %lu", next);

		fib1 = fib2;
		fib2 = next;
	}

	printf("\n");

	return (0);
}


